# Copyright 2022 David Garcia
# See LICENSE file for licensing details.

options:
  zookeeper-properties:
    description: zookeeper.properties configuration file.
    type: string
    default: |
      clientPort=2181
      dataDir=/var/lib/zookeeper/data
      dataLogDir=/var/lib/zookeeper/log
      tickTime=2000
      initLimit=5
      syncLimit=2
      maxClientCnxns=60
      minSessionTimeout=4000
      maxSessionTimeout=40000
      autopurge.snapRetainCount=3
      autopurge.purgeInterval=0
  heap-size:
    description: Heap memory
    type: string
    default: 512M
